### ISSUE TITLE
Call to undefined method Couchbase\ClusterOptions::transactionsOptions()

### ISSUE THREAD

**Issue by karltanjuan** [couchbase/docs-sdk-php#104]
Hi there, I just followed the official documentation and the sample demo but it gives me this kind of error, please check:

https://github.com/couchbase/docs-sdk-php/blob/4b826506e711e83c23853166678359cac92f81ae/modules/howtos/examples/transactions-example.php#L21-L28

Call to undefined method Couchbase\ClusterOptions::transactionsOptions()

Here's my line of code:
`$options->transactionsOptions($transactions_configuration);`

I also imported the:

use \Couchbase\ClusterOptions;
use \Couchbase\Cluster;
use \Couchbase\TransactionsConfiguration;
use Couchbase\TransactionAttemptContext;
use Couchbase\TransactionQueryOptions;
use \Couchbase\DurabilityLevel;
use \Couchbase\QueryOptions;
use \Couchbase\QueryScanConsistency;
use \Couchbase\MutationState;

Take note: I'm using the latest couchbase php sdk version (4)
When I check the ClusterOptions, there is no transactionOptions method, did I miss anything? Thanks.

![image](https://user-images.githubusercontent.com/15957554/176337003-59d400b3-4b17-4968-966e-9631cc8972ec.png)

**Comment by avsej** [comment]
Looks like the sample uses pre-release version of the library. The accessor was renamed to `transactionsConfiguration`

https://github.com/couchbase/couchbase-php-client/blob/81aa802ead79e25af702bae86be7a1cbe89bf6fa/Couchbase/ClusterOptions.php#L480-L490

**Comment by maria-robobug** [comment]
@avsej the docs example was updated, but it's pending review - please have a look at https://github.com/couchbase/docs-sdk-php/pull/103

Once that is merged/approved, the documentation will be up to date.

**Comment by maria-robobug** [comment]
The docs fix has been published, see: 
https://docs.couchbase.com/php-sdk/current/howtos/distributed-acid-transactions-from-the-sdk.html#configuration

Closing this issue.

**Comment by karltanjuan** [comment]
thank you.
