### ISSUE TITLE
positionalParameters does not work

### ISSUE THREAD

**Issue by orangeShadow** [couchbase/docs-sdk-php#81]
Hi, with SDK 3.1 I use in QueryOptions positionParameters, but in SDK 3.2 it's not work, it's bug or it is features

**Comment by osfameron** [comment]
Hi @orangeShadow thanks for the report, I'll have a look. Can you give me a code snippet of what you're calling, and also the error output?

I've created https://issues.couchbase.com/browse/DOC-9279 to track this internally.

**Comment by orangeShadow** [comment]
I have no error, but I have empty result, first i try use string with  ?, then I replace ? to $1 ,.... 
```
$queryOptions = new \Couchbase\QueryOptions();
$queryOptions->positionalParameters($bindings);
$res = $this->getCluster()->query($query, $queryOptions);
```
now, I use this code for working: 
```
preg_match_all('/`(\w+)`\s?[=<>,]+\s?\?/', $query, $matches);

  if (!empty($matches[1])) {
      $bindingsWithName = [];
      $replacer         = [];
      foreach ($matches[1] as $key => $name) {
          $bindingsWithName[$name] = $bindings[$key];
          unset($bindings[$key]);
          $replacer[] = "$$name";
      }
      $query = \Illuminate\Support\Str::replaceArray('?', $replacer, $query);
  }

  $queryOptions = new \Couchbase\QueryOptions();
  $queryOptions->namedParameters($bindingsWithName);
  $res = $this->getCluster()->query($query, $queryOptions);
```

it makes me unhappy :(

**Comment by avsej** [comment]
@orangeShadow, what is your libcouchbase version? should be working with the recent one.

**Comment by orangeShadow** [comment]
3.2.2 runtime version does not work, in 3.1.2 all right

**Comment by osfameron** [comment]
I've run this example https://docs.couchbase.com/php-sdk/current/howtos/n1ql-queries-with-sdk.html#handling-results against a database with `travel-sample` bucket installed, and with latest version of PHP couchbase library.

```
❯ pecl info couchbase
About pecl.php.net/couchbase-3.2.1
```

This gives me results for that example, so I'm unable to replicate the problem. @orangeShadow can you give any more details on how to replicate this issue?

**Comment by orangeShadow** [comment]
hm it's strange, ok I will try to repeat problem with another version
